version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend_network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
